version: '3'
services:
  web:
    build: .
    environment:
      - http_proxy=http://192.168.11.114:7890
      - https_proxy=http://192.168.11.114:7890
      - all_proxy=socks5://192.168.11.114:7890
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
    command: sleep infinity

  school:
    build: .
    environment:
      - http_proxy=http://192.168.11.114:7890
      - https_proxy=http://192.168.11.114:7890
      - all_proxy=socks5://192.168.11.114:7890
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
    command: sleep infinity

  wechat:
    build: .
    environment:
      - http_proxy=http://192.168.11.114:7890
      - https_proxy=http://192.168.11.114:7890
      - all_proxy=socks5://192.168.11.114:7890
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
    command: sleep infinity

  postgres:
    image: postgres:15
    restart: unless-stopped
    shm_size: 512m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.docker/postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"

  memcached:
    image: memcached:1.5.2
    command: -m 2048 -I 100m -vv
    ports:
      - "11211:11211"